/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InboxRouteRouteImport } from './routes/inbox/route'
import { Route as InboxAppRouteRouteImport } from './routes/inbox/_app/route'
import { Route as InboxDefinirSenhaRouteImport } from './routes/inbox/definir-senha'
import { Route as InboxEntrarRouteImport } from './routes/inbox/entrar'
import { Route as ApiInboxAiRouteImport } from './routes/api/inbox/ai'
import { Route as ApiInboxMediaRouteImport } from './routes/api/inbox/media'
import { Route as ApiInboxSendRouteImport } from './routes/api/inbox/send'
import { Route as ApiInboxStatusRouteImport } from './routes/api/inbox/status'
import { Route as ApiWhatsappWebhookRouteImport } from './routes/api/whatsapp/webhook'
import { Route as InboxAppIndexRouteImport } from './routes/inbox/_app/index'
import { Route as InboxAppConfiguracoesRouteImport } from './routes/inbox/_app/configuracoes'
import { Route as InboxAppContatosRouteImport } from './routes/inbox/_app/contatos'
import { Route as InboxAppFunilRouteImport } from './routes/inbox/_app/funil'
import { Route as InboxAppRespostasRouteImport } from './routes/inbox/_app/respostas'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxRouteRoute = InboxRouteRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxAppRouteRoute = InboxAppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => InboxRouteRoute,
} as any)
const InboxDefinirSenhaRoute = InboxDefinirSenhaRouteImport.update({
  id: '/definir-senha',
  path: '/definir-senha',
  getParentRoute: () => InboxRouteRoute,
} as any)
const InboxEntrarRoute = InboxEntrarRouteImport.update({
  id: '/entrar',
  path: '/entrar',
  getParentRoute: () => InboxRouteRoute,
} as any)
const ApiInboxAiRoute = ApiInboxAiRouteImport.update({
  id: '/api/inbox/ai',
  path: '/api/inbox/ai',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInboxMediaRoute = ApiInboxMediaRouteImport.update({
  id: '/api/inbox/media',
  path: '/api/inbox/media',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInboxSendRoute = ApiInboxSendRouteImport.update({
  id: '/api/inbox/send',
  path: '/api/inbox/send',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInboxStatusRoute = ApiInboxStatusRouteImport.update({
  id: '/api/inbox/status',
  path: '/api/inbox/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWhatsappWebhookRoute = ApiWhatsappWebhookRouteImport.update({
  id: '/api/whatsapp/webhook',
  path: '/api/whatsapp/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxAppIndexRoute = InboxAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => InboxAppRouteRoute,
} as any)
const InboxAppConfiguracoesRoute = InboxAppConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => InboxAppRouteRoute,
} as any)
const InboxAppContatosRoute = InboxAppContatosRouteImport.update({
  id: '/contatos',
  path: '/contatos',
  getParentRoute: () => InboxAppRouteRoute,
} as any)
const InboxAppFunilRoute = InboxAppFunilRouteImport.update({
  id: '/funil',
  path: '/funil',
  getParentRoute: () => InboxAppRouteRoute,
} as any)
const InboxAppRespostasRoute = InboxAppRespostasRouteImport.update({
  id: '/respostas',
  path: '/respostas',
  getParentRoute: () => InboxAppRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/inbox': typeof InboxRouteRouteWithChildren
  '/inbox/definir-senha': typeof InboxDefinirSenhaRoute
  '/inbox/entrar': typeof InboxEntrarRoute
  '/api/inbox/ai': typeof ApiInboxAiRoute
  '/api/inbox/media': typeof ApiInboxMediaRoute
  '/api/inbox/send': typeof ApiInboxSendRoute
  '/api/inbox/status': typeof ApiInboxStatusRoute
  '/api/whatsapp/webhook': typeof ApiWhatsappWebhookRoute
  '/inbox/configuracoes': typeof InboxAppConfiguracoesRoute
  '/inbox/contatos': typeof InboxAppContatosRoute
  '/inbox/funil': typeof InboxAppFunilRoute
  '/inbox/respostas': typeof InboxAppRespostasRoute
  '/inbox/': typeof InboxAppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/inbox': typeof InboxAppIndexRoute
  '/inbox/definir-senha': typeof InboxDefinirSenhaRoute
  '/inbox/entrar': typeof InboxEntrarRoute
  '/api/inbox/ai': typeof ApiInboxAiRoute
  '/api/inbox/media': typeof ApiInboxMediaRoute
  '/api/inbox/send': typeof ApiInboxSendRoute
  '/api/inbox/status': typeof ApiInboxStatusRoute
  '/api/whatsapp/webhook': typeof ApiWhatsappWebhookRoute
  '/inbox/configuracoes': typeof InboxAppConfiguracoesRoute
  '/inbox/contatos': typeof InboxAppContatosRoute
  '/inbox/funil': typeof InboxAppFunilRoute
  '/inbox/respostas': typeof InboxAppRespostasRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/inbox': typeof InboxRouteRouteWithChildren
  '/inbox/_app': typeof InboxAppRouteRouteWithChildren
  '/inbox/definir-senha': typeof InboxDefinirSenhaRoute
  '/inbox/entrar': typeof InboxEntrarRoute
  '/api/inbox/ai': typeof ApiInboxAiRoute
  '/api/inbox/media': typeof ApiInboxMediaRoute
  '/api/inbox/send': typeof ApiInboxSendRoute
  '/api/inbox/status': typeof ApiInboxStatusRoute
  '/api/whatsapp/webhook': typeof ApiWhatsappWebhookRoute
  '/inbox/_app/configuracoes': typeof InboxAppConfiguracoesRoute
  '/inbox/_app/contatos': typeof InboxAppContatosRoute
  '/inbox/_app/funil': typeof InboxAppFunilRoute
  '/inbox/_app/respostas': typeof InboxAppRespostasRoute
  '/inbox/_app/': typeof InboxAppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/inbox'
    | '/inbox/definir-senha'
    | '/inbox/entrar'
    | '/api/inbox/ai'
    | '/api/inbox/media'
    | '/api/inbox/send'
    | '/api/inbox/status'
    | '/api/whatsapp/webhook'
    | '/inbox/configuracoes'
    | '/inbox/contatos'
    | '/inbox/funil'
    | '/inbox/respostas'
    | '/inbox/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/inbox'
    | '/inbox/definir-senha'
    | '/inbox/entrar'
    | '/api/inbox/ai'
    | '/api/inbox/media'
    | '/api/inbox/send'
    | '/api/inbox/status'
    | '/api/whatsapp/webhook'
    | '/inbox/configuracoes'
    | '/inbox/contatos'
    | '/inbox/funil'
    | '/inbox/respostas'
  id:
    | '__root__'
    | '/'
    | '/inbox'
    | '/inbox/_app'
    | '/inbox/definir-senha'
    | '/inbox/entrar'
    | '/api/inbox/ai'
    | '/api/inbox/media'
    | '/api/inbox/send'
    | '/api/inbox/status'
    | '/api/whatsapp/webhook'
    | '/inbox/_app/configuracoes'
    | '/inbox/_app/contatos'
    | '/inbox/_app/funil'
    | '/inbox/_app/respostas'
    | '/inbox/_app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  InboxRouteRoute: typeof InboxRouteRouteWithChildren
  ApiInboxAiRoute: typeof ApiInboxAiRoute
  ApiInboxMediaRoute: typeof ApiInboxMediaRoute
  ApiInboxSendRoute: typeof ApiInboxSendRoute
  ApiInboxStatusRoute: typeof ApiInboxStatusRoute
  ApiWhatsappWebhookRoute: typeof ApiWhatsappWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox': {
      id: '/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof InboxRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox/_app': {
      id: '/inbox/_app'
      path: ''
      fullPath: '/inbox'
      preLoaderRoute: typeof InboxAppRouteRouteImport
      parentRoute: typeof InboxRouteRoute
    }
    '/inbox/definir-senha': {
      id: '/inbox/definir-senha'
      path: '/definir-senha'
      fullPath: '/inbox/definir-senha'
      preLoaderRoute: typeof InboxDefinirSenhaRouteImport
      parentRoute: typeof InboxRouteRoute
    }
    '/inbox/entrar': {
      id: '/inbox/entrar'
      path: '/entrar'
      fullPath: '/inbox/entrar'
      preLoaderRoute: typeof InboxEntrarRouteImport
      parentRoute: typeof InboxRouteRoute
    }
    '/api/inbox/ai': {
      id: '/api/inbox/ai'
      path: '/api/inbox/ai'
      fullPath: '/api/inbox/ai'
      preLoaderRoute: typeof ApiInboxAiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/inbox/media': {
      id: '/api/inbox/media'
      path: '/api/inbox/media'
      fullPath: '/api/inbox/media'
      preLoaderRoute: typeof ApiInboxMediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/inbox/send': {
      id: '/api/inbox/send'
      path: '/api/inbox/send'
      fullPath: '/api/inbox/send'
      preLoaderRoute: typeof ApiInboxSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/inbox/status': {
      id: '/api/inbox/status'
      path: '/api/inbox/status'
      fullPath: '/api/inbox/status'
      preLoaderRoute: typeof ApiInboxStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/whatsapp/webhook': {
      id: '/api/whatsapp/webhook'
      path: '/api/whatsapp/webhook'
      fullPath: '/api/whatsapp/webhook'
      preLoaderRoute: typeof ApiWhatsappWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox/_app/': {
      id: '/inbox/_app/'
      path: '/'
      fullPath: '/inbox/'
      preLoaderRoute: typeof InboxAppIndexRouteImport
      parentRoute: typeof InboxAppRouteRoute
    }
    '/inbox/_app/configuracoes': {
      id: '/inbox/_app/configuracoes'
      path: '/configuracoes'
      fullPath: '/inbox/configuracoes'
      preLoaderRoute: typeof InboxAppConfiguracoesRouteImport
      parentRoute: typeof InboxAppRouteRoute
    }
    '/inbox/_app/contatos': {
      id: '/inbox/_app/contatos'
      path: '/contatos'
      fullPath: '/inbox/contatos'
      preLoaderRoute: typeof InboxAppContatosRouteImport
      parentRoute: typeof InboxAppRouteRoute
    }
    '/inbox/_app/funil': {
      id: '/inbox/_app/funil'
      path: '/funil'
      fullPath: '/inbox/funil'
      preLoaderRoute: typeof InboxAppFunilRouteImport
      parentRoute: typeof InboxAppRouteRoute
    }
    '/inbox/_app/respostas': {
      id: '/inbox/_app/respostas'
      path: '/respostas'
      fullPath: '/inbox/respostas'
      preLoaderRoute: typeof InboxAppRespostasRouteImport
      parentRoute: typeof InboxAppRouteRoute
    }
  }
}

interface InboxAppRouteRouteChildren {
  InboxAppConfiguracoesRoute: typeof InboxAppConfiguracoesRoute
  InboxAppContatosRoute: typeof InboxAppContatosRoute
  InboxAppFunilRoute: typeof InboxAppFunilRoute
  InboxAppRespostasRoute: typeof InboxAppRespostasRoute
  InboxAppIndexRoute: typeof InboxAppIndexRoute
}

const InboxAppRouteRouteChildren: InboxAppRouteRouteChildren = {
  InboxAppConfiguracoesRoute: InboxAppConfiguracoesRoute,
  InboxAppContatosRoute: InboxAppContatosRoute,
  InboxAppFunilRoute: InboxAppFunilRoute,
  InboxAppRespostasRoute: InboxAppRespostasRoute,
  InboxAppIndexRoute: InboxAppIndexRoute,
}

const InboxAppRouteRouteWithChildren = InboxAppRouteRoute._addFileChildren(
  InboxAppRouteRouteChildren,
)

interface InboxRouteRouteChildren {
  InboxAppRouteRoute: typeof InboxAppRouteRouteWithChildren
  InboxDefinirSenhaRoute: typeof InboxDefinirSenhaRoute
  InboxEntrarRoute: typeof InboxEntrarRoute
}

const InboxRouteRouteChildren: InboxRouteRouteChildren = {
  InboxAppRouteRoute: InboxAppRouteRouteWithChildren,
  InboxDefinirSenhaRoute: InboxDefinirSenhaRoute,
  InboxEntrarRoute: InboxEntrarRoute,
}

const InboxRouteRouteWithChildren = InboxRouteRoute._addFileChildren(
  InboxRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  InboxRouteRoute: InboxRouteRouteWithChildren,
  ApiInboxAiRoute: ApiInboxAiRoute,
  ApiInboxMediaRoute: ApiInboxMediaRoute,
  ApiInboxSendRoute: ApiInboxSendRoute,
  ApiInboxStatusRoute: ApiInboxStatusRoute,
  ApiWhatsappWebhookRoute: ApiWhatsappWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
