/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedClientesRouteImport } from './routes/_authenticated/clientes'
import { Route as AuthenticatedInboxRouteRouteImport } from './routes/_authenticated/inbox/route'
import { Route as AuthenticatedInboxIndexRouteImport } from './routes/_authenticated/inbox/index'
import { Route as AuthenticatedInboxConfiguracoesRouteImport } from './routes/_authenticated/inbox/configuracoes'
import { Route as AuthenticatedInboxContatosRouteImport } from './routes/_authenticated/inbox/contatos'
import { Route as AuthenticatedInboxFunilRouteImport } from './routes/_authenticated/inbox/funil'
import { Route as AuthenticatedInboxRespostasRouteImport } from './routes/_authenticated/inbox/respostas'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedClientesRoute = AuthenticatedClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInboxRouteRoute = AuthenticatedInboxRouteRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInboxIndexRoute = AuthenticatedInboxIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedInboxRouteRoute,
} as any)
const AuthenticatedInboxConfiguracoesRoute =
  AuthenticatedInboxConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedInboxRouteRoute,
  } as any)
const AuthenticatedInboxContatosRoute =
  AuthenticatedInboxContatosRouteImport.update({
    id: '/contatos',
    path: '/contatos',
    getParentRoute: () => AuthenticatedInboxRouteRoute,
  } as any)
const AuthenticatedInboxFunilRoute = AuthenticatedInboxFunilRouteImport.update({
  id: '/funil',
  path: '/funil',
  getParentRoute: () => AuthenticatedInboxRouteRoute,
} as any)
const AuthenticatedInboxRespostasRoute =
  AuthenticatedInboxRespostasRouteImport.update({
    id: '/respostas',
    path: '/respostas',
    getParentRoute: () => AuthenticatedInboxRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/inbox': typeof AuthenticatedInboxRouteRouteWithChildren
  '/clientes': typeof AuthenticatedClientesRoute
  '/inbox/configuracoes': typeof AuthenticatedInboxConfiguracoesRoute
  '/inbox/contatos': typeof AuthenticatedInboxContatosRoute
  '/inbox/funil': typeof AuthenticatedInboxFunilRoute
  '/inbox/respostas': typeof AuthenticatedInboxRespostasRoute
  '/inbox/': typeof AuthenticatedInboxIndexRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/clientes': typeof AuthenticatedClientesRoute
  '/': typeof AuthenticatedIndexRoute
  '/inbox/configuracoes': typeof AuthenticatedInboxConfiguracoesRoute
  '/inbox/contatos': typeof AuthenticatedInboxContatosRoute
  '/inbox/funil': typeof AuthenticatedInboxFunilRoute
  '/inbox/respostas': typeof AuthenticatedInboxRespostasRoute
  '/inbox': typeof AuthenticatedInboxIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/inbox': typeof AuthenticatedInboxRouteRouteWithChildren
  '/_authenticated/clientes': typeof AuthenticatedClientesRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/inbox/configuracoes': typeof AuthenticatedInboxConfiguracoesRoute
  '/_authenticated/inbox/contatos': typeof AuthenticatedInboxContatosRoute
  '/_authenticated/inbox/funil': typeof AuthenticatedInboxFunilRoute
  '/_authenticated/inbox/respostas': typeof AuthenticatedInboxRespostasRoute
  '/_authenticated/inbox/': typeof AuthenticatedInboxIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/inbox'
    | '/clientes'
    | '/inbox/configuracoes'
    | '/inbox/contatos'
    | '/inbox/funil'
    | '/inbox/respostas'
    | '/inbox/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/reset-password'
    | '/clientes'
    | '/'
    | '/inbox/configuracoes'
    | '/inbox/contatos'
    | '/inbox/funil'
    | '/inbox/respostas'
    | '/inbox'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/_authenticated/inbox'
    | '/_authenticated/clientes'
    | '/_authenticated/'
    | '/_authenticated/inbox/configuracoes'
    | '/_authenticated/inbox/contatos'
    | '/_authenticated/inbox/funil'
    | '/_authenticated/inbox/respostas'
    | '/_authenticated/inbox/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clientes': {
      id: '/_authenticated/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof AuthenticatedClientesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inbox': {
      id: '/_authenticated/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof AuthenticatedInboxRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inbox/': {
      id: '/_authenticated/inbox/'
      path: '/'
      fullPath: '/inbox/'
      preLoaderRoute: typeof AuthenticatedInboxIndexRouteImport
      parentRoute: typeof AuthenticatedInboxRouteRoute
    }
    '/_authenticated/inbox/configuracoes': {
      id: '/_authenticated/inbox/configuracoes'
      path: '/configuracoes'
      fullPath: '/inbox/configuracoes'
      preLoaderRoute: typeof AuthenticatedInboxConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedInboxRouteRoute
    }
    '/_authenticated/inbox/contatos': {
      id: '/_authenticated/inbox/contatos'
      path: '/contatos'
      fullPath: '/inbox/contatos'
      preLoaderRoute: typeof AuthenticatedInboxContatosRouteImport
      parentRoute: typeof AuthenticatedInboxRouteRoute
    }
    '/_authenticated/inbox/funil': {
      id: '/_authenticated/inbox/funil'
      path: '/funil'
      fullPath: '/inbox/funil'
      preLoaderRoute: typeof AuthenticatedInboxFunilRouteImport
      parentRoute: typeof AuthenticatedInboxRouteRoute
    }
    '/_authenticated/inbox/respostas': {
      id: '/_authenticated/inbox/respostas'
      path: '/respostas'
      fullPath: '/inbox/respostas'
      preLoaderRoute: typeof AuthenticatedInboxRespostasRouteImport
      parentRoute: typeof AuthenticatedInboxRouteRoute
    }
  }
}

interface AuthenticatedInboxRouteRouteChildren {
  AuthenticatedInboxConfiguracoesRoute: typeof AuthenticatedInboxConfiguracoesRoute
  AuthenticatedInboxContatosRoute: typeof AuthenticatedInboxContatosRoute
  AuthenticatedInboxFunilRoute: typeof AuthenticatedInboxFunilRoute
  AuthenticatedInboxRespostasRoute: typeof AuthenticatedInboxRespostasRoute
  AuthenticatedInboxIndexRoute: typeof AuthenticatedInboxIndexRoute
}

const AuthenticatedInboxRouteRouteChildren: AuthenticatedInboxRouteRouteChildren =
  {
    AuthenticatedInboxConfiguracoesRoute: AuthenticatedInboxConfiguracoesRoute,
    AuthenticatedInboxContatosRoute: AuthenticatedInboxContatosRoute,
    AuthenticatedInboxFunilRoute: AuthenticatedInboxFunilRoute,
    AuthenticatedInboxRespostasRoute: AuthenticatedInboxRespostasRoute,
    AuthenticatedInboxIndexRoute: AuthenticatedInboxIndexRoute,
  }

const AuthenticatedInboxRouteRouteWithChildren =
  AuthenticatedInboxRouteRoute._addFileChildren(
    AuthenticatedInboxRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedInboxRouteRoute: typeof AuthenticatedInboxRouteRouteWithChildren
  AuthenticatedClientesRoute: typeof AuthenticatedClientesRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedInboxRouteRoute: AuthenticatedInboxRouteRouteWithChildren,
  AuthenticatedClientesRoute: AuthenticatedClientesRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
